[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "targets/x86-64_cobalt.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
